version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - dependencies
      - automated
    groups:
      production-dependencies:
        patterns:
          - '*'
        dependency-type: production
      development-dependencies:
        patterns:
          - '*'
        dependency-type: development

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '04:30'
      timezone: 'America/Sao_Paulo'
    labels:
      - dependencies
      - github-actions
