name: Bug report
description: Report misconduct with minimal evidence.
title: '[Bug]: '
labels: ['bug']
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What were you trying to do?
      placeholder: Explain the scenario and the goal.
    validations:
      required: true
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      placeholder: What actually happened?
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/commit
      placeholder: ex. v0.1.0 or commit hash
